/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Cliente;
import Model.ModeloTabela;
import dao.DAO;
import java.util.ArrayList;

/**
 *
 * @author Luis
 */
public class JCadastro extends javax.swing.JFrame {

    /**
     * Creates new form JCadastro
     */
    private ModeloTabela modeloTabela;

    public JCadastro(ModeloTabela modeloTabela) {
        this.modeloTabela = modeloTabela;
        initComponents();
        //setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); //Isso fecha a aplicação inteira quando a janela é fechada.
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        // Modo de cadastro
        setTitle("Cadastro de Cliente"); // no modo cadastro
        btnIncluirCadastro.setVisible(true);
        btnSalvar.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomeCadastro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCPFCNPJCadastro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTelefoneCadastro = new javax.swing.JTextField();
        txtEmailCadastro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEnderecoCadastro = new javax.swing.JTextArea();
        btnIncluirCadastro = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        txtNomeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCadastroActionPerformed(evt);
            }
        });

        jLabel2.setText("CPF/CNPJ");

        jLabel3.setText("E-mail");

        jLabel4.setText("Telefone");

        jLabel5.setText("Endereço");

        txtEnderecoCadastro.setColumns(20);
        txtEnderecoCadastro.setRows(5);
        jScrollPane1.setViewportView(txtEnderecoCadastro);

        btnIncluirCadastro.setText("Incluir");
        btnIncluirCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirCadastroActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar Alterações");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIncluirCadastro))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeCadastro, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtCPFCNPJCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtTelefoneCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)))
                    .addComponent(txtEmailCadastro, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPFCNPJCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefoneCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluirCadastro)
                    .addComponent(btnSalvar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCadastroActionPerformed

    private void btnIncluirCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirCadastroActionPerformed
        DAO dao = new DAO();
        //dao.cadastrarCliente(new Cliente(null, txtNomeCadastro.getText(), txtCPFCNPJCadastro.getText(), txtEmailCadastro.getText(), txtTelefoneCadastro.getText(), txtEnderecoCadastro.getText()));
        Cliente cliente = new Cliente(null, txtNomeCadastro.getText(), txtCPFCNPJCadastro.getText(),
                txtEmailCadastro.getText(), txtTelefoneCadastro.getText(), txtEnderecoCadastro.getText());

        dao.cadastrarCliente(cliente);
        modeloTabela.adicionarCliente(cliente);
        this.dispose();
    }//GEN-LAST:event_btnIncluirCadastroActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        if (clienteEmEdicao != null) {
            // Atualiza os dados no objeto
            clienteEmEdicao.setCpfCnpj(txtCPFCNPJCadastro.getText());
            clienteEmEdicao.setNome(txtNomeCadastro.getText());
            clienteEmEdicao.setEmail(txtEmailCadastro.getText());
            clienteEmEdicao.setTelefone(txtTelefoneCadastro.getText());
            clienteEmEdicao.setEndereco(txtEnderecoCadastro.getText());

            // Atualiza no banco de dados
            DAO dao = new DAO();
            dao.alterarCliente(clienteEmEdicao);

            // Atualiza a tabela visual
            modeloTabela.atualizarCliente(clienteEmEdicao);

            // Mensagem e fechar
            javax.swing.JOptionPane.showMessageDialog(this, "Cliente alterado com sucesso!");
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Nenhum cliente em edição!");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        ArrayList<Cliente> listaClientes = new ArrayList<>();
        ModeloTabela modeloTabela = new ModeloTabela(listaClientes);
        new JCadastro(modeloTabela).setVisible(true);
    }

    private void preencherCampos(Cliente cliente) {
        txtCPFCNPJCadastro.setText(cliente.getCpfCnpj());
        txtNomeCadastro.setText(cliente.getNome());
        txtEmailCadastro.setText(cliente.getEmail());
        txtTelefoneCadastro.setText(cliente.getTelefone());
        txtEnderecoCadastro.setText(cliente.getEndereco());
    }

    private Cliente clienteEmEdicao;
    //  private ModeloTabela modeloTabela;

    public JCadastro(Cliente cliente, ModeloTabela modeloTabela) {

        setTitle("Alterar Cliente: " + cliente.getNome()); // no modo edição

        this.clienteEmEdicao = cliente;
        this.modeloTabela = modeloTabela;
        initComponents(); // chama os componentes da janela
        preencherCampos(cliente); // método que tu vai criar abaixo
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        // Modo de edição
        btnIncluirCadastro.setVisible(false);
        btnSalvar.setVisible(true);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIncluirCadastro;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCPFCNPJCadastro;
    private javax.swing.JTextField txtEmailCadastro;
    private javax.swing.JTextArea txtEnderecoCadastro;
    private javax.swing.JTextField txtNomeCadastro;
    private javax.swing.JTextField txtTelefoneCadastro;
    // End of variables declaration//GEN-END:variables
}
